title: course github
tagline: A brand new course on Learning Lab
description: github train course
template:
  repo: course-github-template
  name: course-github
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
